# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  Конфигурация хоста:                                                         ║
# ╠══════════════════════════════════════════════════════════════════════════════╣
# ║  Это главный файл конфигурации для конкретного компьютера (хоста).           ║
# ║                                                                              ║
# ║  ЧТО ЗДЕСЬ ПРОИСХОДИТ:                                                       ║
# ║  1. Импортируются все модули (системные, desktop, hardware, users)           ║
# ║  2. Устанавливается hostname — имя компьютера в сети                         ║
# ║  3. Фиксируется stateVersion — версия NixOS при первой установке             ║
# ║                                                                              ║
# ║  ПОРЯДОК ЗАГРУЗКИ:                                                           ║
# ║  flake.nix → hosts/matebook/default.nix → modules/*.nix → home/*.nix         ║
# ╚══════════════════════════════════════════════════════════════════════════════╝
{ config, pkgs, inputs, lib, ... }:

{
  imports = [
    # Hardware configuration (generated by nixos-generate-config)
    ./hardware.nix
    
    # System modules
    ../../modules/system/boot.nix
    ../../modules/system/filesystem.nix
    ../../modules/system/networking.nix
    ../../modules/system/locale.nix
    ../../modules/system/nix.nix
    ../../modules/system/impermanence.nix
    
    # Hardware modules
    ../../modules/hardware/intel.nix
    
    # Desktop modules
    ../../modules/desktop/hyprland.nix
    ../../modules/desktop/audio.nix
    ../../modules/desktop/fonts.nix
    
    # User modules
    ../../modules/users/aleksandr.nix
  ];

  # Hostname
  networking.hostName = "matebook";

  # System version - do not change
  system.stateVersion = "24.11";
}
